### ISSUE TITLE
Unable to use it using the below code

### ISSUE THREAD

**Issue by hg0605** [csvignesh/image-to-text#2]
//this file and image are in same folder

var imageToTextDecoder = require('image-to-text');
var fs=require('fs');
 /*
 var file = {
   name: 'b.jpg',
    path: './'  
 };
 */
 //path: './image/'
fs.readFile('abcd.png', function(err, content){
if(err)
    console.log(err);
else
{
console.log(content);
var file = {
   name: 'abcd.png',
    content:content  
 };
 imageToTextDecoder.getKeywordsForImage(file).then(function(keywords){
    console.log("Harsh");
    console.log(keywords);
 }).fail(function(){
        console.log('with name alone as string : failed');
    });
}
});

**Comment by csvignesh** [comment]
The module internally uses cloudsiteapi to decode the image. You can register on couldsiteapi to get a key.

 var key = 'ztEX9VMpdh3YbmiGfvlLDA'; //Your key registered from cloudsightapi @ https://cloudsightapi.com 
 imageToTextDecoder.setAuth(key);
 imageToTextDecoder.getKeywordsForImage(file).then(function(keywords){
    console.log(keywords);
 },function(error){
    console.log(error);
 });

**Comment by hg0605** [comment]
thanks!
